projects:
  - name: finance
    queues_default:
      notify_base: "http://localhost:8080"
      notify_timeout: 5
      retry_times: 5
      retry_duration: 300
      binding_exchange: fishtrip
    queues:
      - queue_name: "processor"
        notify_path: "xxx" #例子
        routing_key:
          - "order.state.paid"
      - queue_name: "wakasms.orders"
        notify_path: "xxx" #例子
        routing_key:
          - "order.state.*"
